### ISSUE TITLE
Agregar animacion a los botones

### ISSUE THREAD

**Issue by camilanoeli** [camilanoeli/WasteMate#3]
Se debe agregar animacion a los botones para tener un indicador visual de que fueron presionados.

**Comment by camilanoeli** [comment]
Se logró agregar animación por medio de un drawable, tenemos tres opciones actualmente para analizar y mejorar:
- press_effect.xml
- ripple_button.xml
- ripple_button2.xml

**Comment by rodrigoDambrosio** [comment]
Fixeado con ripple_button.xml
